/**
 * File content templates for create-rainbow-app
 */

// Wagmi configuration template
const wagmiTemplate = `import { getDefaultConfig } from "@rainbow-me/rainbowkit";
import { mainnet, polygon, optimism, arbitrum, base } from "viem/chains";
import { createStorage } from "wagmi";

export const config = getDefaultConfig({
	appName: "My RainbowKit App",
	projectId: "YOUR_PROJECT_ID",
	storage: createStorage({ key: "my-app" }),
	chains: [mainnet, polygon, optimism, arbitrum, base],
	ssr: true, // If your dApp uses server side rendering (SSR)
});
`;

// Fonts template (shared by both routers)
const fontsTemplate = `import { Geist, Geist_Mono } from "next/font/google";

export const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});
`;

// Demo ABI template
const demoAbiTemplate = [
	{
		inputs: [
			{
				internalType: "string",
				name: "_greeting",
				type: "string",
			},
		],
		name: "setGreeting",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "greeting",
		outputs: [
			{
				internalType: "string",
				name: "",
				type: "string",
			},
		],
		stateMutability: "view",
		type: "function",
	},
];

// App Router templates
const appRouter = {
	provider: `"use client";

import { config } from "@/wagmi";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";

const queryClient = new QueryClient();

export default function Provider({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<WagmiProvider config={config}>
			<QueryClientProvider client={queryClient}>
				<RainbowKitProvider>{children}</RainbowKitProvider>
			</QueryClientProvider>
		</WagmiProvider>
	);
}
`,

	layout: `import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/lib/fonts";
import "@rainbow-me/rainbowkit/styles.css";
import Provider from "@/provider/web3provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}
			>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
`,

	page: `import { ConnectButton } from "@rainbow-me/rainbowkit";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { geistMono, geistSans } from "@/lib/fonts";

export default function Home() {
	return (
		<div
			className={\`\${geistSans.className} \${geistMono.className} grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]\`}
		>
			<main className="flex flex-col gap-10 row-start-2 items-center sm:items-start">
				<div className="flex flex-col items-center gap-4">
					<h1 className="text-4xl font-bold text-center">
						Web3 Dapp Template
					</h1>
					<p className="text-lg text-center text-gray-600 dark:text-gray-400">
						Web3 dApp template with Next.js, TypeScript, Tailwind
						CSS & shadcn/ui
					</p>
				</div>

				<div className="flex flex-col items-center justify-center gap-6 w-full">
					<ConnectButton />

					<div className="w-full p-6 border border-gray-200 dark:border-gray-800 rounded-lg">
						<h2 className="text-xl font-semibold mb-4 text-center">
							Get Started
						</h2>
						<ol className="list-inside list-decimal text-sm space-y-2 font-[family-name:var(--font-geist-mono)]">
							<li>
								Edit{" "}
								<code className="bg-black/[.05] dark:bg-white/[.06] px-1 py-0.5 rounded font-semibold">
									src/app/page.tsx
								</code>
							</li>
							<li>
								Update your project ID in{" "}
								<code className="bg-black/[.05] dark:bg-white/[.06] px-1 py-0.5 rounded font-semibold">
									src/wagmi.ts
								</code>
							</li>
							<li>Add shadcn/ui components as needed</li>
							<li>Build your Web3 application!</li>
						</ol>
					</div>
				</div>

				<div className="flex gap-4 items-center flex-col sm:flex-row">
					<Link
						href="https://rainbowkit.com/docs"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Button variant="secondary">RainbowKit Docs</Button>
					</Link>
					<Link
						href="https://ui.shadcn.com"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Button variant="outline">shadcn/ui</Button>
					</Link>
				</div>
			</main>

			<footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center text-sm text-gray-500">
				<span>Built with Web3 Dapp Template</span>
			</footer>
		</div>
	);
}
`,
};

// Pages Router templates
const pagesRouter = {
	provider: `"use client";

import { config } from "@/wagmi";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";

const queryClient = new QueryClient();

export default function Provider({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<WagmiProvider config={config}>
			<QueryClientProvider client={queryClient}>
				<RainbowKitProvider>{children}</RainbowKitProvider>
			</QueryClientProvider>
		</WagmiProvider>
	);
}
`,

	app: `import "@/styles/globals.css";
import type { AppProps } from "next/app";
import "@rainbow-me/rainbowkit/styles.css";
import Provider from "@/provider/web3provider";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<Provider>
			<Component {...pageProps} />
		</Provider>
	);
}
`,

	index: `import { ConnectButton } from "@rainbow-me/rainbowkit";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { geistMono, geistSans } from "@/lib/fonts";

export default function Home() {
	return (
		<div
			className={\`\${geistSans.className} \${geistMono.className} grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]\`}
		>
			<main className="flex flex-col gap-10 row-start-2 items-center sm:items-start">
				<div className="flex flex-col items-center gap-4">
					<h1 className="text-4xl font-bold text-center">
						Web3 Dapp Template
					</h1>
					<p className="text-lg text-center text-gray-600 dark:text-gray-400">
						Web3 dApp template with Next.js, TypeScript, Tailwind
						CSS & shadcn/ui
					</p>
				</div>

				<div className="flex flex-col items-center justify-center gap-6 w-full">
					<ConnectButton />

					<div className="w-full p-6 border border-gray-200 dark:border-gray-800 rounded-lg">
						<h2 className="text-xl font-semibold mb-4 text-center">
							Get Started
						</h2>
						<ol className="list-inside list-decimal text-sm space-y-2 font-[family-name:var(--font-geist-mono)]">
							<li>
								Edit{" "}
								<code className="bg-black/[.05] dark:bg-white/[.06] px-1 py-0.5 rounded font-semibold">
									src/pages/index.tsx
								</code>
							</li>
							<li>
								Update your project ID in{" "}
								<code className="bg-black/[.05] dark:bg-white/[.06] px-1 py-0.5 rounded font-semibold">
									src/wagmi.ts
								</code>
							</li>
							<li>Add shadcn/ui components as needed</li>
							<li>Build your Web3 application!</li>
						</ol>
					</div>
				</div>

				<div className="flex gap-4 items-center flex-col sm:flex-row">
					<Link
						href="https://rainbowkit.com/docs"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Button variant="secondary">RainbowKit Docs</Button>
					</Link>
					<Link
						href="https://ui.shadcn.com"
						target="_blank"
						rel="noopener noreferrer"
					>
						<Button variant="outline">shadcn/ui</Button>
					</Link>
				</div>
			</main>

			<footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center text-sm text-gray-500">
				<span>Built with Web3 Dapp Template</span>
			</footer>
		</div>
	);
}
`,
};

module.exports = {
	wagmiTemplate,
	fontsTemplate,
	demoAbiTemplate,
	appRouter,
	pagesRouter,
};
