name: Publish Package to npm

on:
    push:
        branches: [main]
        tags: ["v*"]
    workflow_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm ci || npm install

            - name: Check for version changes
              id: check_version
              run: |
                  # Get remote version from npm registry
                  REMOTE_VERSION=$(npm view create-rainbow-app version 2>/dev/null || echo "0.0.0")

                  # Get local version from package.json
                  LOCAL_VERSION=$(node -e "console.log(require('./package.json').version);")

                  echo "Remote version on npm: $REMOTE_VERSION"
                  echo "Local version: $LOCAL_VERSION"

                  if [ "$REMOTE_VERSION" != "$LOCAL_VERSION" ]; then
                    echo "Version has changed, will publish"
                    echo "version_changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "Version unchanged, will skip unless manually triggered"
                    echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Publish to npm Registry
              if: steps.check_version.outputs.version_changed == 'true' || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
